services:
  web:
    build:
      context: .
      target: runner
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJXM2FoRC1EZE95VHhOYWRud3R2SjZjQk9wSUsxc0x0QjVhQTlvaElUZVprIn0.eyJleHAiOjE3NTU0MDI3NzIsImlhdCI6MTc1NTM3Mzk3MiwianRpIjoiYTVhMThmZWMtYzgwMy00ZDcwLTg3NWEtYmI0NmFmYWJlMzgxIiwiaXNzIjoiaHR0cDovLzE3Mi4xNi43MC4yMDo4MDgwL3JlYWxtcy9uZWJpbSIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiI1ZjlmYTMzMy1kNDhlLTQ1YmQtYjY0OC0zYjM3ODQyNWJiNzEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJzZWNpbHN0b3JlIiwic2lkIjoiYjZkODgwZjAtOTU3OC00MjQ1LWE0NWUtNDgzOTRiZDA2YWQ0IiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyIqIiwiLyoiXSwic2NvcGUiOiJvcGVuaWQgZW1haWwgcHJvZmlsZSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwibmFtZSI6Ik11bmx1IE11bmx1IiwicHJlZmVycmVkX3VzZXJuYW1lIjoibXVubHU0MDM3QGdtYWlsLmNvbSIsImdpdmVuX25hbWUiOiJNdW5sdSIsImZhbWlseV9uYW1lIjoiTXVubHUiLCJlbWFpbCI6Im11bmx1NDAzN0BnbWFpbC5jb20ifQ.Y51QvarP-vHkjP8of7UroiLgLNXCwr-G-Ua9B4GPBehmK5OxtbHNVBRw_tHzy4-B16eEot4KZS_X2WWNE1iU06_ofoB8-Qx_Bn_wJMCtCnH6SE3h-Hv95A1cr2LKa00YLVdoRX8jQMVij8WVKkN4-yaSZvznQ9gfvWwDmCPNneBKudg57Fxr-6CMu006Emt7dWnJUi9AKEuZeT5qpoajK5YXLmQepcwNbR0ZcX1gEhwI1yYZkQ4-0xvyD6j5_k6lyCCa-8A_8yc0Vov2QKtXUfo8Az-ZM0S7I45L5E6JRkb2lwBEBuvc2Epq9IZhDyGVAMqvSofuMwsvJz0FQZgLDQ
